development:
  adapter: postgresql
  encoding: unicode
  database: development
  host: localhost
  pool: 5
  template: template0
  username: postgres 
  password: Wi2fRIMyY4GNFBCLn7MG 

test:
  adapter: postgresql
  encoding: unicode
  database: test
  host: localhost
  pool: 5
  template: template0
  username: postgres
  password: Wi2fRIMyY4GNFBCLn7MG 

production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: localhost
  pool: 5
  template: template0
  username: postgres
  password: Wi2fRIMyY4GNFBCLn7MG
